algoritmo "repetiçãoUserContar"
// Função :
// Autor :
// Data : 11/08/2021
// Seção de Declarações 
var
      contar, Nuser, salto: inteiro
inicio
      Escreva(" Número que deseja contar? ")
       Leia (Nuser)
      Escreva("De quanto em quanto deseja contar? ")
      Leia (salto)
      contar <- 0
      Enquanto (contar <= Nuser) faca
          Escreval(contar)
               contar <- contar + salto
      FimEnquanto
fimalgoritmo
